[package]
name = "magnet-zither"
version = "0.1.0"
authors = ["Ben Wolsieffer <benwolsieffer@gmail.com>"]
edition = "2021"

[dependencies]
atsamd-hal = { version = "0.13.0", features = ["rtic"] }
cortex-m = "0.7.3"
cortex-m-rt = "0.7.0"
cortex-m-rtic = "0.6.0-rc.4"
embedded-hal = "0.2.6"
libm = "0.2.1"
panic-halt = "0.2.0"
#samd-dma = { path = "../../samd-dma", features = ["samd21e"] }
trinket_m0 = "0.11.0"
heapless = "0.7.8"
err-derive = { version = "0.3.0", default-features = false }

[patch.crates-io]
atsamd-hal = { path = "../../atsamd/hal" }
trinket_m0 = { path = "../../atsamd/boards/trinket_m0" }

[profile.release]
# symbols are nice and they don't increase the size on Flash
debug = true

